// Explicit live test: uses a small request on the signed-in Copilot account.
import { _electron as electron } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const temp = await mkdtemp(path.join(tmpdir(), 'assistant-desktop-'));
const executablePath = path.join(root, 'dist/Laptop Assistant-win32-x64/Laptop Assistant.exe');
const env = { ...process.env, ASSISTANT_TEST_PROFILE: path.join(temp, 'profile') };
delete env.ELECTRON_RUN_AS_NODE;
let desktop;
try {
  desktop = await electron.launch({ executablePath, env, timeout: 60000 });
  const page = await desktop.firstWindow();
  const errors = [];
  const approvals = setInterval(() => {
    page.getByRole('button', { name: 'Allow once', exact: true }).click({ timeout: 500 }).catch(() => {});
  }, 700);
  page.on('close', () => clearInterval(approvals));
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#connection').filter({ hasText: 'Connected to GitHub Copilot' }).waitFor({ timeout: 120000 });
  assert.equal(await page.title(), 'Laptop Assistant');
  assert.equal(await page.locator('h1').innerText(), 'What can I help with?');
  assert.equal(await page.evaluate(() => typeof window.desktop.bootstrap), 'function');
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight), true);
  await page.screenshot({ path: path.join(temp, 'desktop.png') });
  await page.locator('#sidebar-toggle').click();
  assert.ok(await page.locator('body').evaluate(el => el.classList.contains('sidebar-collapsed')));
  await page.locator('#sidebar-toggle').click();
  await page.locator('#folder-toggle').click();
  await desktop.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }); }, root);
  await page.locator('#browse-folder').click();
  assert.equal(await page.locator('#folder').inputValue(), root);
  await page.locator('#folder-toggle').click();
  await page.locator('#model').selectOption('gpt-5-mini');
  const target = path.join(temp, 'desktop-test.txt');
  const marker = `DESKTOP_OK_${Date.now()}`;
  await page.locator('#prompt').fill(`Integration test: create ${JSON.stringify(target)} containing exactly ${marker}. Use a filesystem or shell tool, then read the file to verify it. Only change that file. Reply with a short Markdown bullet list describing the result and include the marker in inline code.`);
  await page.locator('#send').click();
  await page.locator('#stop').waitFor({ state: 'visible' });
  await page.locator('#stop').waitFor({ state: 'hidden', timeout: 240000 });
  console.log('Live response:', await page.locator('#messages').innerText());
  assert.equal((await readFile(target, 'utf8')).trim(), marker);
  assert.ok(await page.locator('.message.assistant code').count() > 0);
  assert.ok(await page.locator('#tool-list .tool').count() > 0);
  await page.locator('.copy-message').last().click();
  await page.locator('.copy-message').last().filter({ hasText: 'Copied' }).waitFor();
  assert.match(await desktop.evaluate(({ clipboard }) => clipboard.readText()), new RegExp(marker));
  await page.locator('#search-chats').fill('nothing-matches-this-chat');
  assert.equal(await page.locator('.chat-item:visible').count(), 0);
  await page.locator('#search-chats').fill('Integration test');
  assert.equal(await page.locator('.chat-item:visible').count(), 1);
  await page.screenshot({ path: path.join(temp, 'chat.png') });
  assert.deepEqual(errors, []);
  const oldURL = page.url();
  await desktop.close();
  desktop = undefined;
  await assert.rejects(fetch(oldURL));
  desktop = await electron.launch({ executablePath, env, timeout: 60000 });
  const reopened = await desktop.firstWindow();
  await reopened.locator('.chat-item').first().waitFor({ timeout: 120000 });
  await reopened.locator('.chat-item').first().click();
  await reopened.locator('.message.assistant').first().waitFor();
  assert.match(await reopened.locator('#messages').innerText(), new RegExp(marker));
  console.log('PASS: packaged Windows app, Copilot authentication, file write/read, native folder picker, Markdown, clipboard, chat search, persistence after exit, service shutdown.');
  console.log('Screenshots:', temp);
} finally {
  await desktop?.close();
  await rm(path.join(temp, 'desktop-test.txt'), { force: true });
}
